# hash:sha256:08cccb70a90af4806da6298cfdd1d373f7dd1e45fa4f95b7d6aa6c0a4ab67cb0
ARG REGISTRY_HOST
FROM $REGISTRY_HOST/codeocean/jupyterlab:3.0.9-miniconda4.9.2-python3.8-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

ARG GIT_ASKPASS
ARG GIT_ACCESS_TOKEN
COPY git-askpass /

RUN pip3 install -U --no-cache-dir \
    imageio==2.34.2 \
    matplotlib==3.7.5 \
    numpy==1.24.4 \
    pandas==2.0.2 \
    scikit-learn==1.3.2
